/**
 * @vitest-environment node
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

describe('Icon Generation Script (Integration)', () => {
  const resourcesDir = path.join(__dirname, '..', '..', 'resources');
  const sourceIconPath = path.join(resourcesDir, 'icon.png');
  const icoIconPath = path.join(resourcesDir, 'icon.ico');
  const icnsIconPath = path.join(resourcesDir, 'icon.icns');

  describe('Source Icons Exist', () => {
    it('should have source icon.png', () => {
      expect(fs.existsSync(sourceIconPath)).toBe(true);
      const stats = fs.statSync(sourceIconPath);
      expect(stats.size).toBeGreaterThan(0);
    });

    it('should have icon.icns for macOS', () => {
      expect(fs.existsSync(icnsIconPath)).toBe(true);
      const stats = fs.statSync(icnsIconPath);
      expect(stats.size).toBeGreaterThan(0);
    });
  });

  describe('Generated Icons', () => {
    it('should have icon.ico for Windows', () => {
      // icon.ico should exist (generated by npm run generate-icons)
      expect(fs.existsSync(icoIconPath)).toBe(true);
      const stats = fs.statSync(icoIconPath);
      expect(stats.size).toBeGreaterThan(0);
    });

    it('icon.ico should be a valid ICO file', () => {
      const buffer = fs.readFileSync(icoIconPath);
      // ICO files start with these magic bytes: 0x00 0x00 0x01 0x00
      expect(buffer[0]).toBe(0x00);
      expect(buffer[1]).toBe(0x00);
      expect(buffer[2]).toBe(0x01);
      expect(buffer[3]).toBe(0x00);
    });
  });

  describe('Script Module', () => {
    it('should export generateIcons function', async () => {
      const scriptModule = await import('../../scripts/generate-icons');
      expect(scriptModule.generateIcons).toBeDefined();
      expect(typeof scriptModule.generateIcons).toBe('function');
    });
  });

  describe('npm Script', () => {
    it('should have generate-icons script in package.json', () => {
      const packageJsonPath = path.join(__dirname, '..', '..', 'package.json');
      const packageJson = JSON.parse(
        fs.readFileSync(packageJsonPath, 'utf-8')
      );
      expect(packageJson.scripts['generate-icons']).toBeDefined();
      expect(packageJson.scripts['generate-icons']).toContain(
        'scripts/generate-icons.js'
      );
    });
  });

  describe('Forge Configuration', () => {
    it('should reference icon files in forge.config.ts', () => {
      const forgeConfigPath = path.join(
        __dirname,
        '..',
        '..',
        'forge.config.ts'
      );
      const forgeConfig = fs.readFileSync(forgeConfigPath, 'utf-8');

      // Check icon references
      expect(forgeConfig).toContain('./resources/icon.ico');
      expect(forgeConfig).toContain('./resources/icon.icns');
      expect(forgeConfig).toContain('./resources/icon.png');
    });

    it('should configure setupIcon for Windows maker', () => {
      const forgeConfigPath = path.join(
        __dirname,
        '..',
        '..',
        'forge.config.ts'
      );
      const forgeConfig = fs.readFileSync(forgeConfigPath, 'utf-8');

      expect(forgeConfig).toContain("setupIcon: './resources/icon.ico'");
    });
  });
});
